language: node_js

node_js: 
  - "node"

cache: yarn

notifications:
  email: false

install:
  - yarn

script:
  - yarn test

before_deploy:
  - yarn global add now

deploy:
  - NOW_DEPLOYMENT=$(now --token=$NOW_TOKEN --team oslopride --no-clipboard)

after_deploy:
  - if [ "$TRAVIS_PULL_REQUEST" ] then; curl -H "Authorization: token ${PRIDEBOT_TOKEN}" -X POST -d "{\"body\": \"${NOW_DEPLOYMENT}\"}" "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments"; fi
  - now alias set $NOW_DEPLOYMENT oslopride.now.sh --token=$NOW_TOKEN --team oslopride