language: node_js

node_js: 
  - "node"

cache: yarn

notifications:
  email: false

branches:
  only:
  - master
  - /^v([0-9]+)\.([0-9]+)\.([0-9]+)$/

install:
  - yarn
  - yarn global add now

script:
  - yarn test
  - yarn build

after_success:
  - ./scripts/deploy-now.sh