language: node_js

node_js: 
  - "node"

cache: yarn

notifications:
  email: false

install:
  - yarn
  - yarn global add now

script:
  - yarn test

after_success:
  - NOW_DEPLOYMENT=$(now --token=$NOW_TOKEN --team oslopride --no-clipboard)
  - ./scripts/pridebot-comment.sh
  - if [ "$TRAVIS_BRANCH" = "master" ]; then now alias set $NOW_DEPLOYMENT oslopride.now.sh --token=$NOW_TOKEN --team oslopride; fi